-- Disposable identities only. No real account, message, avatar or presence changes persist.
begin;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid();
 sa uuid:=gen_random_uuid(); sb uuid:=gen_random_uuid(); sc uuid:=gen_random_uuid();
 instance uuid:=gen_random_uuid(); new_instance uuid:=gen_random_uuid();
 na text:='PresA'||left(replace(a::text,'-',''),12); nb text:='PresB'||left(replace(b::text,'-',''),12);
 nc text:='PresC'||left(replace(c::text,'-',''),12); result jsonb; started timestamptz; oid uuid:=gen_random_uuid(); eid uuid:=gen_random_uuid(); fid uuid:=gen_random_uuid(); attempt uuid:=gen_random_uuid(); code text:='PAW-BETA-IW0-SP2-RM1-SG0-LM1-RU1-CL0-OOS1-PS0';
begin
 insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values
 (a,a::text||'@example.invalid',now(),jsonb_build_object('nickname',na)),
 (b,b::text||'@example.invalid',now(),jsonb_build_object('nickname',nb)),
 (c,c::text||'@example.invalid',now(),jsonb_build_object('nickname',nc));
 insert into auth.sessions(id,user_id) values(sa,a),(sb,b),(sc,c);
 insert into paw_private.launcher_sessions(player_id,session_id,session_started_at,launcher_id)
 values(a,sa,now(),instance),(b,sb,now(),instance),(c,sc,now(),instance);
 perform set_config('request.headers',jsonb_build_object('x-paw-launcher',instance)::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 set local role authenticated;
 if public.paw_presence(true,'beta','{"core":true,"colors":false}')->>'status'<>'ok' then raise exception 'presence write'; end if;
 begin perform 1 from paw_private.social_presence;raise exception 'direct private read allowed';exception when insufficient_privilege then null;end;
 begin perform public.paw_friend_avatar_allowed(a,sa,instance,b);raise exception 'client can call service helper';exception when insufficient_privilege then null;end;
 if public.paw_presence(true,'evil','{}')->>'status'<>'invalid_presence' then raise exception 'channel validation'; end if;
 if public.paw_presence(true,'beta','{"path":"private"}')->>'status'<>'invalid_presence' then raise exception 'metadata validation'; end if;
 if public.paw_presence(true,'beta','{"core":"true"}')->>'status'<>'invalid_presence' then raise exception 'boolean validation'; end if;
 if public.paw_friend_action('request',candidate:=nb)->>'status'<>'ok' then raise exception 'request'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 result:=public.paw_social_list()->'players'->0;
 if result?'presence' or result?'components' or result?'avatar_revision' then raise exception 'pending request leaks detail';end if;
 if public.paw_friend_action('accept',a)->>'status'<>'ok' then raise exception 'accept'; end if;
 result:=public.paw_social_list()->'players'->0;
 if result->>'presence'<>'playing' or result->>'channel'<>'beta' or result->'components'<>'{"core":true,"colors":false}'::jsonb
 or result->>'playing_since' is null then raise exception 'friend details missing';end if;
 started:=(result->>'playing_since')::timestamptz;

 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 result:=public.paw_offer_create(b,oid,'config',code,null,null,null);
 if result->>'status'<>'ok' or result->'offer'->>'state'<>'pending' then raise exception 'offer creation: %',result;end if;
 if public.paw_offer_create(b,oid,'config',code,null,null,null)->>'status'<>'ok' then raise exception 'idempotency';end if;
 if public.paw_offer_create(b,oid,'config',replace(code,'SP2','SP4'),null,null,null)->>'status'<>'message_conflict' then raise exception 'mutated duplicate';end if;
 if public.paw_offer_action(oid,'decline',null)->>'status'<>'offer_unavailable' then raise exception 'sender accepted own offer';end if;
 begin perform 1 from paw_private.social_offers;raise exception 'private offers readable';exception when insufficient_privilege then null;end;
 begin perform public.paw_transfer_cleanup_candidates();raise exception 'client cleanup callable';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',c,'session_id',sc,'role','authenticated')::text,true);
 if public.paw_offers(a)->>'status'<>'friend_required' then raise exception 'outsider reads offers';end if;
 if public.paw_offer_action(oid,'begin',attempt)->>'status'<>'offer_unavailable' then raise exception 'outsider accepts';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 result:=public.paw_offers(a);
 if jsonb_array_length(result->'offers')<>1 or result->'offers'->0->>'configuration'<>code then raise exception 'immutable snapshot not returned: %',result;end if;
 if public.paw_offer_action(oid,'begin',attempt)->'offer'->>'state'<>'applying' then raise exception 'begin';end if;
 if public.paw_offer_action(oid,'complete',gen_random_uuid())->>'status'<>'offer_unavailable' then raise exception 'wrong attempt finished';end if;
 reset role;
 update paw_private.social_offers set apply_until=now()-interval '1 second' where id=oid;
 set local role authenticated;
 if public.paw_offers(a)->'offers'->0->>'state'<>'failed' then raise exception 'lost client did not fail';end if;
 if public.paw_offer_action(oid,'complete',attempt)->'offer'->>'state'<>'accepted' then raise exception 'late durable success rejected';end if;
 if public.paw_offer_action(oid,'complete',attempt)->'offer'->>'state'<>'accepted' then raise exception 'duplicate completion';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 if public.paw_offers(b)->'offers'->0->>'state'<>'accepted' then raise exception 'sender did not see status';end if;
 perform public.paw_offer_create(b,eid,'config',code,null,null,null);
 reset role;
 update paw_private.social_offers set expires_at=now()-interval '1 second' where id=eid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 set local role authenticated;
 if public.paw_offer_action(eid,'begin',attempt)->>'status'<>'offer_expired' then raise exception 'expired offer accepted';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 result:=public.paw_offer_create(b,fid,'save',null,'Тест.rsg',16,repeat('a',64));
 if result->>'status'<>'ok' or result->'offer'->>'state'<>'uploading' then raise exception 'save reservation: %',result;end if;
 if exists(select 1 from public.paw_messages where sender_id=a and message_id=fid) then raise exception 'unverified save became message';end if;
 if public.paw_offer_create(b,gen_random_uuid(),'save',null,'../evil.rsg',16,repeat('a',64))->>'status'<>'invalid_save' then raise exception 'unsafe save name';end if;
 if public.paw_offer_create(b,gen_random_uuid(),'save',null,'test.rsg',20971521,repeat('a',64))->>'status'<>'invalid_save' then raise exception 'oversized save';end if;
 reset role;
 if public.paw_transfer_authorize(b,sb,instance,fid,'download')->>'status'='ok' then raise exception 'unaccepted download';end if;
 if public.paw_transfer_authorize(c,sc,instance,fid,'upload')->>'status'='ok' then raise exception 'outsider upload';end if;
 if public.paw_transfer_authorize(a,sa,instance,fid,'upload')->>'status'<>'ok' then raise exception 'owner upload denied';end if;
 if public.paw_transfer_ready(a,sa,instance,fid)->>'status'<>'ok' then raise exception 'ready';end if;
 if public.paw_transfer_ready(a,sa,instance,fid)->>'status'<>'ok' then raise exception 'ready idempotency';end if;
 if (select count(*) from public.paw_messages where sender_id=a and message_id=fid)<>1 then raise exception 'duplicate save message';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 set local role authenticated;
 if public.paw_offer_action(fid,'begin',attempt)->>'status'<>'ok' then raise exception 'save acceptance';end if;
 reset role;
 if public.paw_transfer_authorize(b,sb,instance,fid,'download')->>'status'<>'ok' then raise exception 'accepted download denied';end if;
 if public.paw_transfer_authorize(b,sb,new_instance,fid,'download')->>'status'<>'session_replaced' then raise exception 'wrong launcher download';end if;
 set local role authenticated;
 if public.paw_offer_action(fid,'fail',attempt)->'offer'->>'state'<>'failed' then raise exception 'explicit failure';end if;
 if public.paw_offer_action(fid,'complete',attempt)->>'status'<>'offer_unavailable' then raise exception 'explicit failure became success';end if;
 reset role;
 if jsonb_array_length(public.paw_transfer_cleanup_candidates())<1 then raise exception 'no cleanup';end if;
 if (select public from storage.buckets where id='paw-social-saves') then raise exception 'public save bucket';end if;
 if has_function_privilege('anon','public.paw_offers(uuid)','execute')
 or has_function_privilege('anon','public.paw_offer_action(uuid,text,uuid)','execute')
 or has_function_privilege('authenticated','public.paw_transfer_authorize(uuid,uuid,uuid,uuid,text)','execute')
 or has_function_privilege('authenticated','public.paw_transfer_ready(uuid,uuid,uuid,uuid)','execute')
 then raise exception 'public/service grant boundary';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 set local role authenticated;
 perform public.paw_offer_create(b,gen_random_uuid(),'config',code,null,null,null);
 perform public.paw_offer_create(b,gen_random_uuid(),'config',code,null,null,null);
 if public.paw_offer_create(b,gen_random_uuid(),'config',code,null,null,null)->>'status'<>'rate_limit' then raise exception 'offer rate bound';end if;
 reset role;
 update paw_private.social_offers set created_at=now()-interval '2 minutes' where sender_id=a;
 perform public.paw_transfer_cleaned(array[a::text||'/'||fid::text||'.rsg']);
 set local role authenticated;
 if public.paw_offer_create(b,gen_random_uuid(),'save',null,'one.rsg',20971520,repeat('b',64))->>'status'<>'ok' then raise exception 'first bounded reservation';end if;
 if public.paw_offer_create(b,gen_random_uuid(),'save',null,'two.rsg',20971520,repeat('c',64))->>'status'<>'ok' then raise exception 'second bounded reservation';end if;
 if public.paw_offer_create(b,gen_random_uuid(),'save',null,'three.rsg',11534336,repeat('d',64))->>'status'<>'storage_limit' then raise exception '50 MiB storage bound';end if;
 reset role;
 set local role authenticated;

 reset role;
 if not public.paw_friend_avatar_allowed(b,sb,instance,a) then raise exception 'friend avatar denied';end if;
 if public.paw_friend_avatar_allowed(c,sc,instance,a) then raise exception 'stranger avatar permitted';end if;
 if paw_private.friend_presence(c,a)<>'{}'::jsonb then raise exception 'stranger presence permitted';end if;
 update paw_private.social_presence set seen_at=now()-interval '5 seconds' where player_id=a;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 set local role authenticated;
 perform public.paw_presence(true,'beta','{"core":true}');
 reset role;
 if (select playing_since from paw_private.social_presence where player_id=a)<>started then raise exception 'playing duration reset';end if;
 update paw_private.social_presence set seen_at=now()-interval '41 seconds' where player_id=a;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 set local role authenticated;
 result:=public.paw_social_list()->'players'->0;
 if result->>'presence'<>'offline' or result->>'playing_since' is not null or result->>'last_seen' is null then raise exception 'TTL offline';end if;
 reset role;
 update paw_private.social_presence set seen_at=now() where player_id=a;
 update paw_private.launcher_sessions set launcher_id=new_instance where player_id=a;
 if paw_private.friend_presence(b,a)->>'presence'<>'offline' then raise exception 'takeover retained stale presence';end if;
 if public.paw_friend_avatar_allowed(a,sa,instance,b) then raise exception 'stale instance avatar permitted';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 set local role authenticated;
 if public.paw_presence(false,'stable','{}')->>'status'<>'session_expired' then raise exception 'stale instance wrote presence';end if;
 reset role;
 update paw_private.launcher_sessions set launcher_id=instance where player_id=a;
 update paw_private.social_presence set seen_at=now()-interval '5 seconds' where player_id=a;
 set local role authenticated;
 perform public.paw_presence(false,'stable','{"core":true}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 if public.paw_social_list()->'players'->0->>'presence'<>'online' then raise exception 'game exit online';end if;
 if public.paw_friend_action('block',a)->>'status'<>'ok' then raise exception 'block';end if;
 if public.paw_offers(a)->>'status'<>'friend_required' then raise exception 'blocked offers visible';end if;
 if public.paw_offer_action(oid,'complete',attempt)->>'status'<>'friend_required' then raise exception 'blocked status mutation';end if;
 result:=public.paw_social_list()->'players'->0;
 if result?'presence' or result?'components' or result?'avatar_revision' then raise exception 'block leaks detail';end if;
 reset role;
 update paw_private.social_offers set state='applying',apply_until=now()+interval '1 minute' where id=fid;
 if public.paw_transfer_authorize(b,sb,instance,fid,'download')->>'status'='ok' then raise exception 'block save download';end if;
 if public.paw_friend_avatar_allowed(b,sb,instance,a) or public.paw_friend_avatar_allowed(a,sa,instance,b) then raise exception 'block avatar access';end if;
 if paw_private.friend_presence(a,b)<>'{}'::jsonb or paw_private.friend_presence(b,a)<>'{}'::jsonb then raise exception 'block presence access';end if;
 raise notice 'SOCIAL OFFERS PASS: immutable payload, live auth/friend privacy, recipient/attempt states, late receipt, server expiry, bounded save, no message before validation, service-only cleanup; friend-only metadata/avatar, pending/stranger/block denial, no direct access, TTL, duration, game exit, takeover and bounded input';
end; $$;
rollback;
