"""Build a bounded gameplay-camera zoom detour, without scanning or polling."""
import argparse, json, struct, sys
from pathlib import Path
sys.dont_write_bytecode = True

HOOK = 0x175D2D
GUARD = bytes.fromhex('558bec51f30f104d0856578bf9f30f10870c0200000f2fc1f30f109710020000f30f118f08020000f30f114508760af30f118708020000eb170f2fcaf30f114d08760df30f119708020000f30f115508')

def build(ks, image, cave):
    code = f'''
      pushfd
      cmp dword ptr [edi], {image + 0x4C385C}
      jne done
      cmp dword ptr [edi+0x20C], 0x3F000000
      jne done
      cmp dword ptr [edi+0x148], 0x3F800000
      jne done
      cmp dword ptr [edi+0x218], 0x41700000
      jne done
      cmp dword ptr [edi+0x210], 0x3F9AE148
      je max_ok
      cmp dword ptr [edi+0x210], 0x40000000
      jne done
    max_ok:
      cmp dword ptr [edi+0x14C], 0x44000000
      je far_ok
      cmp dword ptr [edi+0x14C], 0x44800000
      jne done
    far_ok:
      mov dword ptr [edi+0x210], 0x40000000
      mov dword ptr [edi+0x14C], 0x44800000
    done:
      popfd
      movss xmm0, [edi+0x20C]
      jmp {image + HOOK + 8}
    '''
    return bytes(ks.asm(code, cave)[0])

def main():
    p=argparse.ArgumentParser();p.add_argument('--legacy',type=Path,required=True);p.add_argument('--out',type=Path,required=True);a=p.parse_args()
    sys.path.insert(0,str(a.legacy/'lobby_colors_1372/deps_r15'))
    from keystone import Ks, KS_ARCH_X86, KS_MODE_32
    ks=Ks(KS_ARCH_X86,KS_MODE_32)
    raw=(a.legacy/'k2_runtime_1372_20260904.bin').read_bytes()
    assert raw[0x175D20:0x175D20+len(GUARD)]==GUARD
    assert struct.unpack_from('<4I',raw,0x4C385C)==tuple(0x460000+x for x in (0x176FBF,0x177451,0x380640,0x380C80))
    image,cave=0x460000,0x10000000;code=build(ks,image,cave)
    # The only absolute image operand is the first CMP; the last JMP is relative.
    assert code[:3]==bytes.fromhex('9c813f') and code[-5]==0xe9
    fixups=[(3,True,False),(len(code)-4,True,True)]
    for ib,cb in [(0xE40000,0x21000000),(0x12000000,0x60000000),(0x740000,0x31000000)]:
        b=bytearray(code)
        for off,im,cv in fixups:
            struct.pack_into('<I',b,off,(struct.unpack_from('<I',b,off)[0]+ib-image-(cb-cave if cv else 0))&0xffffffff)
        assert bytes(b)==build(ks,ib,cb)
    a.out.mkdir(parents=True,exist_ok=True)
    (a.out/'camera.bin').write_bytes(code)
    (a.out/'camera.json').write_text(json.dumps(dict(image=image,cave=cave,fixups=fixups,hook=HOOK,guard=GUARD.hex()),indent=2))
    src='// Generated by build_native.py.\nusing System;\ninternal static class CameraZoomPayload {\n internal static byte[] Build(uint image,uint cave) {\n byte[] b=TerrainPatch.Hex("'+code.hex()+'");\n'
    for off,im,cv in fixups:
        src+=f' Add(b,{off},unchecked(image-0x460000'+('-cave+0x10000000' if cv else '')+'));\n'
    src+=' return b;\n }\n static void Add(byte[] b,int o,uint d){Buffer.BlockCopy(BitConverter.GetBytes(unchecked(BitConverter.ToUInt32(b,o)+d)),0,b,o,4);}\n}\n'
    (a.out/'CameraZoomPayload.cs').write_text(src)
    print('CAMERA_BUILD_PASS: bounded gameplay zoom 2; scoped far plane 1024; two relocations; no polling')

if __name__=='__main__':main()
