"""Re-arm a missing native organization-position event; never choose a position."""
import argparse, hashlib, json, struct, sys
from pathlib import Path
sys.dont_write_bytecode = True
HOOK = 0x218666
ORIGINAL = bytes.fromhex('e868c2ffff')
GUARD = bytes.fromhex('8bce') + ORIGINAL + bytes.fromhex('84c0750aff76408bce')

def build(ks, image, cave):
    return bytes(ks.asm(f'''
        push ecx
        call {image+0x2148d3}
        pushfd
        pushad
        mov esi,[esp+36]
        sub esp,528
        lea eax,[esp+15]
        and eax,0xfffffff0
        fxsave [eax]
        push eax
        inc dword ptr [{cave+0x1000}]
        test byte ptr [esp+560],0xff
        jnz done
        cmp dword ptr [esi],{image+0x4e1ae0}
        jne done
        mov edi,[esi+4]
        test edi,edi
        jz done
        cmp [edi+0x7c],esi
        jne done
        test byte ptr [edi+8],1
        jnz done
        cmp dword ptr [edi+0x70],0
        je done
        mov eax,[esi+0xbc]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        mov eax,[esi+0xc0]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        mov eax,[edi+0x20]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        mov eax,[edi+0x24]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        movss xmm0,[esi+0xbc]
        ucomiss xmm0,[edi+0x20]
        jne needs_update
        movss xmm0,[esi+0xc0]
        ucomiss xmm0,[edi+0x24]
        je done
    needs_update:
        lea ebx,[esi+8]
        mov eax,[ebx+4]
        mov edx,64
    next_event:
        test eax,eax
        jz rearm
        cmp [eax],ebx
        jne done
        cmp byte ptr [eax+0x18],0
        jne advance
        cmp dword ptr [eax+0x14],1
        je done
    advance:
        mov eax,[eax+0x10]
        dec edx
        jnz next_event
        jmp done
    rearm:
        push 1
        mov ecx,ebx
        call {image+0x2922ed}
        inc dword ptr [{cave+0x1004}]
        mov eax,[edi+0x14]
        mov [{cave+0x1008}],eax
    done:
        pop eax
        fxrstor [eax]
        add esp,528
        popad
        popfd
        lea esp,[esp+4]
        ret
    ''', cave)[0])

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--legacy',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);a=ap.parse_args()
    sys.path[:0]=[str(a.legacy/'lobby_colors_1372/deps_r15'),str(a.legacy/'pydeps_readable')]
    from keystone import Ks,KS_ARCH_X86,KS_MODE_32
    from capstone import Cs,CS_ARCH_X86,CS_MODE_32,CS_OP_MEM,CS_OP_IMM
    raw=(a.legacy/'k2_runtime_1372_20260904.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()=='b865d8206990c4f055c51de857f0b09b88ab5ee3b6ae74ee5232134001aa591c'
    assert raw[HOOK:HOOK+5]==ORIGINAL
    assert raw[HOOK-2:HOOK-2+len(GUARD)]==GUARD,raw[HOOK-2:HOOK+20].hex()
    ks=Ks(KS_ARCH_X86,KS_MODE_32);md=Cs(CS_ARCH_X86,CS_MODE_32);md.detail=True
    image,cave=0x460000,0x10000000;code=build(ks,image,cave);fixups=[]
    for ins in md.disasm(code,cave):
        for op in ins.operands:
            if op.type==CS_OP_MEM and not op.mem.base and not op.mem.index and cave<=op.mem.disp<cave+8192:
                fixups.append((ins.address-cave+ins.disp_offset,0,1))
            elif op.type==CS_OP_IMM:
                if image<=op.imm<image+0x690000:
                    fixups.append((ins.address-cave+ins.imm_offset,1,-1 if ins.mnemonic in ('call','jmp') else 0))
    for ib,cb in [(0xE40000,0x21000000),(0x12000000,0x60000000),(0x740000,0x31000000)]:
        relocated=bytearray(code)
        for off,im,cv in fixups:
            struct.pack_into('<I',relocated,off,(struct.unpack_from('<I',relocated,off)[0]+im*(ib-image)+cv*(cb-cave))&0xffffffff)
        assert bytes(relocated)==build(ks,ib,cb)
    assert len(code)<0xfc0
    a.out.mkdir(parents=True,exist_ok=True)
    (a.out/'company-position.bin').write_bytes(code)
    (a.out/'company-position.json').write_text(json.dumps(dict(image=image,cave=cave,hook=HOOK,guard=GUARD.hex(),fixups=fixups),indent=2))
    src='// Generated by build_native.py.\nusing System;\ninternal static class CompanyPositionPayload {\n internal static byte[] Build(uint image,uint cave) {\n byte[] b=TerrainPatch.Hex("'+code.hex()+'");\n'
    for off,im,cv in fixups:
        expr=[]
        if im:expr.append('(image-0x460000)')
        if cv==1:expr.append('(cave-0x10000000)')
        elif cv==-1:expr.append('(0x10000000-cave)')
        src+=f' Add(b,{off},unchecked({"+".join(expr)}));\n'
    src+=' return b;\n }\n static void Add(byte[] b,int o,uint d){Buffer.BlockCopy(BitConverter.GetBytes(unchecked(BitConverter.ToUInt32(b,o)+d)),0,b,o,4);}\n}\n'
    (a.out/'CompanyPositionPayload.cs').write_text(src)
    print(f'COMPANY_POSITION_BUILD_PASS: {len(code)} bytes, {len(fixups)} relocations; native event only')

if __name__=='__main__':main()
