import assert from 'node:assert/strict';
export async function communityTests(db,login,rpc,user,peer,admin){
 let checks=0;const check=(v,s)=>{assert.ok(v,s);checks++;};
 const query=(sql,params=[])=>db.query(sql,params);
 const anonymous=async()=>{await db.exec(`reset role;select set_config('request.jwt.claims','{}',false);set role anon`);};
 const denied=async(fn,s)=>{let bad=false;try{await fn();}catch{bad=true;}check(bad,s);};
 const id='7d18c3f2-9062-40ef-bb03-66af00000001';
 await anonymous();
 check((await rpc('paw_community_read',['ru'])).messages.length===0,'guest may read empty RU');
 await denied(()=>rpc('paw_community_send',['ru',id,'anonymous']), 'guest cannot send');
 await denied(()=>query('select * from paw_private.community_messages'),'guest cannot enumerate private storage');
 await login(user);
 check((await rpc('paw_community_send',['zz',id,'bad channel'])).status==='invalid_message','unknown channel rejected');
 for(const body of ['', '   ', 'x'.repeat(1001), 'control\u0001'])check((await rpc('paw_community_send',['ru',id,body])).status==='invalid_message','bad body rejected');
 const sent=await rpc('paw_community_send',['ru',id,'Ищу напарника 🙂']);check(sent.status==='ok','member sends');
 check((await rpc('paw_community_send',['ru',id,'Ищу напарника 🙂'])).message.ordinal===sent.message.ordinal,'retry is idempotent before rate limit');
 check((await rpc('paw_community_send',['en',id,'Ищу напарника 🙂'])).status==='message_conflict','same id cannot switch channels');
 check((await rpc('paw_community_send',['ru',id,'changed'])).status==='message_conflict','same id cannot change text');
 check((await rpc('paw_community_send',['en','7d18c3f2-9062-40ef-bb03-66af00000002','spam'])).status==='rate_limit','rate limit covers both languages');
 await denied(()=>query('insert into paw_private.community_messages(message_id,sender_id,channel,body) values(gen_random_uuid(),$1,\'ru\',\'bypass\')',[user]),'member cannot bypass RPC');
 await anonymous();
 const read=await rpc('paw_community_read',['ru']);check(read.messages.length===1&&read.messages[0].body==='Ищу напарника 🙂','guest receives public text');
 const unchanged=await rpc('paw_community_read',['ru',read.revision]);check(unchanged.unchanged&&!unchanged.messages,'unchanged history is not retransmitted');
 check(Object.keys(read.messages[0]).sort().join(',')==='admin_level,avatar_revision,body,created_at,display_name,message_id,nickname,ordinal,removed,sender_id','read contains public identity only');
 check((await rpc('paw_community_read',['en'])).messages.length===0,'language histories isolated');
 check(await rpc('paw_community_avatar_allowed',[user+'/avatar.jpg'])===true,'guest may read active chat author avatar');
 check(await rpc('paw_community_avatar_allowed',[peer+'/avatar.jpg'])===false,'non-author avatar stays private');
 check(await rpc('paw_community_avatar_allowed',[user+'/other.jpg'])===false,'only fixed avatar object');
 check(await rpc('paw_community_avatar_allowed',['../'+user+'/avatar.jpg'])===false,'path traversal rejected');
 await db.exec('reset role;begin');
 await query(`update public.paw_profiles set avatar_changed_at=now() where id=$1`,[user]);
 await anonymous();
 const changedAvatar=await rpc('paw_community_read',['ru',read.revision]);
 check(!changedAvatar.unchanged&&changedAvatar.messages[0].avatar_revision,'avatar changes invalidate chat revision');
 await db.exec(`reset role;alter table storage.objects enable row level security;grant usage on schema storage to anon;grant select on storage.objects to anon`);
 await query(`insert into storage.objects(bucket_id,name) values('paw-avatars',$1),('paw-avatars',$2),('other',$1)`,[user+'/avatar.jpg',peer+'/avatar.jpg']);
 await anonymous();
 check((await query('select name from storage.objects')).rows.length===1,'RLS exposes only author fixed avatar in correct bucket');
 await db.exec('reset role');
 await query(`update public.paw_profiles set deletion_pending=true where id=$1`,[user]);
 await anonymous();check((await query('select name from storage.objects')).rows.length===0,'deleted account avatar denied');
 await db.exec('rollback;reset role;begin');
 await query(`delete from paw_private.social_presence`);
 await query(`insert into paw_private.social_presence(player_id,session_id,launcher_id,seen_at,channel,components)
 values($1,$1,'20000000-0000-0000-0000-000000000001',now(),'stable','{}'),($2,$2,'20000000-0000-0000-0000-000000000001',now()-interval '41 seconds','stable','{}')`,[user,peer]);
 await anonymous();
 const online=await rpc('paw_community_online',[]);
 check(online.online===1&&Object.keys(online).sort().join(',')==='online,status','aggregate counts fresh sessions only, no identities');
 await db.exec('reset role');
 await query(`update paw_private.social_presence set launcher_id=gen_random_uuid() where player_id=$1`,[user]);
 await anonymous();check((await rpc('paw_community_online',[])).online===0,'replaced launcher session not counted');
 await denied(()=>query('select * from paw_private.social_presence'),'guest cannot enumerate online users');
 await db.exec('rollback;reset role');await anonymous();

 await login(peer);check((await rpc('paw_community_remove',[id])).status==='admin_required','other player cannot delete');
 await login(user);check((await rpc('paw_community_remove',[id])).status==='ok','author can delete');
 await anonymous();const removed=(await rpc('paw_community_read',['ru'])).messages[0];check(removed.removed&&removed.body==='','deleted text never leaves server');
 check((await rpc('paw_community_read',['ru',read.revision])).messages[0].removed,'removal invalidates snapshot revision');
 await db.exec('reset role');
 await query(`update paw_private.community_messages set created_at=clock_timestamp()-interval '1 minute'`);
 await login(user);check((await rpc('paw_community_send',['en','7d18c3f2-9062-40ef-bb03-66af00000003','English chat'])).status==='ok','English send');
 await login(admin);check((await rpc('paw_community_remove',['7d18c3f2-9062-40ef-bb03-66af00000003'])).status==='ok','moderator removes');
 await db.exec('reset role');await query(`update public.paw_profiles set banned_at=now(),ban_reason='fixture' where id=$1`,[user]);
 await login(user);check((await rpc('paw_community_send',['ru','7d18c3f2-9062-40ef-bb03-66af00000004','banned'])).status==='account_banned','ban enforced');
 await db.exec('reset role');await query(`update public.paw_profiles set banned_at=null,ban_reason='' where id=$1`,[user]);
 // Bounded newest window, stable order, account deletion does not disclose identity.
 await query(`insert into paw_private.community_messages(message_id,sender_id,channel,body)
 select gen_random_uuid(),$1,'ru','fixture '||n from generate_series(1,110) n`,[peer]);
 await anonymous();const latest=(await rpc('paw_community_read',['ru'])).messages;check(latest.length===100,'bounded 100 message window');
 check(latest.every((m,i)=>i===0||m.ordinal>latest[i-1].ordinal),'strict stable chronology');
 const older=await rpc('paw_community_read',['ru',null,latest[0].ordinal]);
 check(older.messages.length===11&&!older.more&&older.messages.at(-1).ordinal<latest[0].ordinal,'older page has no overlaps or gaps');
 check((await rpc('paw_community_read',['zz'])).status==='invalid_message','invalid public channel rejected');
 check((await rpc('paw_community_read',['ru',null,0])).status==='invalid_message','invalid cursor rejected');
 await db.exec('reset role');await query(`update public.paw_profiles set deletion_pending=true where id=$1`,[peer]);
 await anonymous();check((await rpc('paw_community_read',['ru'])).messages.every(m=>m.sender_id!==peer),'pending deletion hidden');
 await db.exec('reset role');await query(`update public.paw_profiles set deletion_pending=false where id=$1`,[peer]);
 // The same total in another language must neither trigger nor lose retention.
 await db.exec('truncate paw_private.community_messages restart identity');
 await query(`insert into paw_private.community_messages(message_id,sender_id,channel,body,created_at)
 select gen_random_uuid(),$1,c,'fixture '||n,now()-interval '1 day'
 from unnest(array['ru','en']) c cross join generate_series(1,9999) n`,[peer]);
 await anonymous();const beforeTrim=await rpc('paw_community_read',['ru']);
 check(beforeTrim.more&&beforeTrim.messages.length===100,'large history still has bounded responses');
 await login(user);const thresholdId='7d18c3f2-9062-40ef-bb03-66af00000005';
 const threshold=await rpc('paw_community_send',['ru',thresholdId,':ch_sword: 🙂']);check(threshold.status==='ok','threshold send succeeds');
 check((await rpc('paw_community_send',['ru',thresholdId,':ch_sword: 🙂'])).message.ordinal===threshold.message.ordinal,'retry of threshold send does not trim again');
 await db.exec('reset role');
 check(Number((await query(`select count(*) n from paw_private.community_messages where channel='ru'`)).rows[0].n)===5000,'RU trims precisely 5000 at 10000');
 check(Number((await query(`select count(*) n from paw_private.community_messages where channel='en'`)).rows[0].n)===9999,'EN unaffected by RU retention');
 await anonymous();const trimmed=await rpc('paw_community_read',['ru',beforeTrim.revision]);
 check(trimmed.trimmed&&trimmed.history_revision>beforeTrim.history_revision&&!trimmed.unchanged,'trim invalidates latest and old page revisions');
 let page=trimmed;const seen=new Set();let pages=0;
 do{pages++;for(const m of page.messages){check(!seen.has(m.ordinal),'history cursor never duplicates a retained row');seen.add(m.ordinal);}
  if(!page.more)break;page=await rpc('paw_community_read',['ru',null,page.messages[0].ordinal]);
 }while(pages<60);
 check(pages===50&&seen.size===5000,'entire retained history reachable in 50 bounded pages');
 const oldest=page.messages[0];
 await login(peer);check((await rpc('paw_community_remove',[oldest.message_id])).status==='ok','old message author can remove');
 await anonymous();const moderated=await rpc('paw_community_read',['ru',trimmed.revision]);
 check(!moderated.unchanged&&moderated.history_revision>trimmed.history_revision,'moderation outside latest page invalidates old client cache');
 await db.exec('reset role');await query(`update public.paw_profiles set display_name='Community rename' where id=$1`,[peer]);
 await anonymous();const renamed=await rpc('paw_community_read',['ru',moderated.revision]);
 check(renamed.history_revision>moderated.history_revision,'identity changes invalidate old cached pages');
 await db.exec('reset role');await query(`update paw_private.community_messages set created_at=now()-interval '1 day' where message_id=$1`,[thresholdId]);
 await login(user);check((await rpc('paw_community_send',['en','7d18c3f2-9062-40ef-bb03-66af00000006','English threshold'])).status==='ok','EN reaches its own threshold');
 await db.exec('reset role');
 check(Number((await query(`select count(*) n from paw_private.community_messages where channel='en'`)).rows[0].n)===5000,'EN independently keeps newest 5000');
 check(Number((await query(`select removed_count n from paw_private.community_history where channel='en'`)).rows[0].n)===5000,'server records cleanup count');
 await anonymous();await denied(()=>query('select * from paw_private.community_history'),'retention metadata table remains private');
 await db.exec('reset role');
 await db.exec('truncate paw_private.community_messages restart identity');
 console.log('COMMUNITY SQL PASS',checks);return checks;
}
