"""Display-only resource formatting hooks; no changes to economic values."""
import argparse,hashlib,json,struct,sys
from pathlib import Path

SITES=[(0x2bcdf6,7,0x483ddc,0),(0x2bce93,5,0x5075d4,0x200),(0x2bcd2b,5,0x5075ac,0x400)]
ID='kingdom_points_consumed\0'
FORMATS=['%.7g','/%.7g ','%lc%.7g%s']

def build(ks,image,cave):
    data=bytearray(0xa00); spans=[]
    for i,(site,size,fmt,off) in enumerate(SITES):
        # push sites must reproduce their stack effect; the mov site must not.
        reserve='push 0;' if size==5 else ''
        resource='mov esi,[esp+0x40];' if i==2 else 'mov esi,[ebp+0xc];'
        asm=f'''{reserve} pushfd; pushad;
            mov eax,{image+fmt}; {resource}
            test esi,esi; jz done; mov esi,[esi+8]; test esi,esi; jz done;
            mov edi,{cave+0x800}; mov ecx,{len(ID)}; cld; repe cmpsw; jne done;
            mov eax,{cave+0x880+i*0x40};
        done: mov [esp+36],eax; popad; popfd; jmp {image+site+size};'''
        code=bytes(ks.asm(asm,cave+off)[0]);assert len(code)<0x200
        data[off:off+len(code)]=code;spans.append((off,len(code)))
    def put(off,s):data[off:off+len(s.encode('utf-16-le'))]=s.encode('utf-16-le')
    put(0x800,ID)
    for i,f in enumerate(FORMATS):put(0x880+i*0x40,f+'\0')
    return bytes(data),spans

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--legacy',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);a=ap.parse_args()
    sys.path[:0]=[str(a.legacy/'lobby_colors_1372/deps_r15'),str(a.legacy/'pydeps_readable')]
    from keystone import Ks,KS_ARCH_X86,KS_MODE_32
    from capstone import Cs,CS_ARCH_X86,CS_MODE_32,CS_OP_IMM
    raw=(a.legacy/'k2_runtime_1372_20260904.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()=='b865d8206990c4f055c51de857f0b09b88ab5ee3b6ae74ee5232134001aa591c'
    originals=[]
    for site,size,fmt,_ in SITES:
        b=(b'\xc7\x04\x24' if size==7 else b'\x68')+struct.pack('<I',0x460000+fmt)
        assert raw[site:site+size]==b;originals.append(b.hex())
    ks=Ks(KS_ARCH_X86,KS_MODE_32);md=Cs(CS_ARCH_X86,CS_MODE_32);md.detail=True
    code,spans=build(ks,0x460000,0x10000000);fixups=[]
    for off,n in spans:
        for ins in md.disasm(code[off:off+n],0x10000000+off):
            for op in ins.operands:
                if op.type!=CS_OP_IMM:continue
                im=cv=0
                if 0x460000<=op.imm<0xaf0000:im=1;cv=-1 if ins.mnemonic=='jmp' else 0
                elif 0x10000000<=op.imm<0x10000a00 and ins.mnemonic=='mov':cv=1
                if im or cv:fixups.append((ins.address-0x10000000+ins.imm_offset,im,cv))
    for ib,cb in [(0xe40000,0x21000000),(0x12000000,0x60000000)]:
        r=bytearray(code)
        for off,im,cv in fixups:struct.pack_into('<I',r,off,(struct.unpack_from('<I',r,off)[0]+im*(ib-0x460000)+cv*(cb-0x10000000))&0xffffffff)
        assert bytes(r)==build(ks,ib,cb)[0]
    a.out.mkdir(parents=True,exist_ok=True)
    (a.out/'payload.bin').write_bytes(code)
    (a.out/'payload.json').write_text(json.dumps(dict(sites=SITES,fixups=fixups,originals=originals),indent=2))
    src='// Generated by build_native.py\nusing System;\ninternal static class FractionalPointsPayload {\ninternal static byte[] Build(uint image,uint cave) {\nbyte[] b=TerrainPatch.Hex("'+code.hex()+'");\n'
    for off,im,cv in fixups:
        parts=[]
        if im:parts.append('(image-0x460000)')
        if cv:parts.append('(cave-0x10000000)' if cv==1 else '(0x10000000-cave)')
        src+=f'Add(b,{off},unchecked({"+".join(parts)}));\n'
    src+='return b;}\nstatic void Add(byte[] b,int o,uint d){Buffer.BlockCopy(BitConverter.GetBytes(unchecked(BitConverter.ToUInt32(b,o)+d)),0,b,o,4);}\n}\n'
    (a.out/'FractionalPointsPayload.cs').write_text(src)
    print('FRACTIONAL_POINTS_BUILD_PASS',len(fixups),'relocations')
if __name__=='__main__':main()
