namespace PawsPatchLauncher;

public sealed class Localization
{
    private string _language;

    public Localization(string language) => _language = Normalize(language);

    public string Language => _language;
    public void SetLanguage(string language) => _language = Normalize(language);

    public string this[string key]
        => Strings.TryGetValue(key, out var value) ? (_language == "en" ? value.En : value.Ru) : key;

    private static string Normalize(string language) => language.Equals("en", StringComparison.OrdinalIgnoreCase) ? "en" : "ru";

    private static readonly Dictionary<string, (string Ru, string En)> Strings = new()
    {
        ["app.title"] = ("Paw's Patch для Kohan II", "Paw's Patch for Kohan II"),
        ["app.subtitle"] = ("Arcane Wars · центр обновлений", "Arcane Wars · update center"),
        ["nav.home"] = ("Главная", "Home"),
        ["nav.modules"] = ("Компоненты", "Components"),
        ["nav.settings"] = ("Настройки", "Settings"),
        ["status.ready"] = ("Готово к игре", "Ready to play"),
        ["status.notinstalled"] = ("Патч не установлен", "Patch is not installed"),
        ["status.notfound"] = ("Kohan II не найден", "Kohan II not found"),
        ["status.feedmissing"] = ("Сервер обновлений ещё не подключён", "Update server is not configured yet"),
        ["game.path"] = ("Папка игры", "Game folder"),
        ["game.version"] = ("Версия игры", "Game version"),
        ["patch.version"] = ("Версия патча", "Patch version"),
        ["modules.title"] = ("Компоненты патча", "Patch components"),
        ["modules.core"] = ("Arcane Wars + Paw's Patch", "Arcane Wars + Paw's Patch"),
        ["modules.core.desc"] = ("Основные данные, баланс, новые логова и семейства", "Core data, balance, new lairs and families"),
        ["modules.core.help"] = ("Обязательная основа: Arcane Wars и безопасные исправления Paw's Patch. Её нельзя отключить, потому что остальные компоненты используют эти файлы.", "Required base: Arcane Wars and the safe Paw's Patch fixes. It cannot be disabled because all other components use these files."),
        ["modules.ru"] = ("Русская локализация", "Russian localization"),
        ["modules.ru.desc"] = ("Перевод оригинальной игры, Arcane Wars и новых настроек", "Translation for the base game, Arcane Wars and new settings"),
        ["modules.ru.help"] = ("Устанавливает русский перевод игры, Arcane Wars и Paw's Patch. На игровую симуляцию не влияет и может отличаться у игроков.", "Installs the Russian translation for the game, Arcane Wars and Paw's Patch. It does not affect simulation and may differ between players."),
        ["modules.colors"] = ("Расширенные цвета игроков", "Extended player colors"),
        ["modules.colors.desc"] = ("51 цвет в лобби · экспериментально", "51 lobby colors · experimental"),
        ["modules.colors.help"] = ("Добавляет выбор из 51 цвета в лобби. Функция экспериментальная и должна быть установлена у всех участников сетевой игры.", "Adds 51 selectable lobby colors. This feature is experimental and must be installed by every multiplayer participant."),
        ["channel.beta"] = ("Бета", "Beta"),
        ["channel.beta.tip"] = ("Тестовые функции и ранние обновления", "Test features and early updates"),
        ["home.welcome.title"] = ("Автоматические обновления", "Automatic updates"),
        ["home.welcome.body"] = ("Лаунчер следит за обновлениями активного канала в фоне. Проверка выполняется при запуске, при смене канала и раз в минуту.", "The launcher monitors the active channel in the background. It checks at startup, after switching channels, and once per minute."),
        ["settings.title"] = ("Настройки лаунчера", "Launcher settings"),
        ["settings.language"] = ("Язык интерфейса", "Interface language"),
        ["settings.language.desc"] = ("Переключает русский и английский язык лаунчера", "Switches the launcher between Russian and English"),
        ["settings.beta"] = ("Канал Beta", "Beta channel"),
        ["settings.beta.desc"] = ("Ранние функции для тестирования; Stable сохраняет последнюю проверенную версию", "Early features for testing; Stable keeps the latest accepted version"),
        ["settings.repair"] = ("Проверка файлов", "File verification"),
        ["settings.repair.desc"] = ("Проверяет установленные файлы Paw's Patch и сообщает, если они повреждены, изменены или отсутствуют.", "Checks the installed Paw's Patch files and reports any damaged, modified or missing files."),
        ["settings.updates.desc"] = ("Обновления проверяются раз в минуту. Для выбранного канала заранее загружаются все варианты настроек.", "Updates are checked once per minute. Every settings variant for the selected channel is downloaded in advance."),
        ["button.checknow"] = ("Проверить обновления", "Check for updates"),
        ["button.launcherupdate"] = ("Обновить лаунчер до {0}", "Update launcher to {0}"),
        ["button.patchupdate"] = ("Обновить {0}", "Update {0}"),
        ["button.install"] = ("Установить", "Install"),
        ["button.installed"] = ("Установлено", "Installed"),
        ["install.patch.title"] = ("Paw's Patch готов к установке", "Paw's Patch is ready to install"),
        ["install.patch.body"] = ("Лаунчер загрузит Arcane Wars, Paw's Patch и все варианты настроек выбранного канала.", "The launcher will download Arcane Wars, Paw's Patch and every settings variant for the selected channel."),
        ["update.patch.title"] = ("Доступно обновление {0}", "{0} update available"),
        ["update.patch.body"] = ("Будут загружены все новые компоненты выбранного канала. Переключение уже загруженных настроек выполняется локально перед запуском игры.", "All new components for the selected channel will be downloaded. Already downloaded settings are switched locally before the game starts."),
        ["update.launcher.ready"] = ("Доступна новая версия лаунчера: {0}", "A new launcher version is available: {0}"),
        ["updates.current"] = ("Установлена актуальная версия {0}", "The current {0} version is installed"),
        ["updates.checked"] = ("Последняя проверка: {0}", "Last checked: {0}"),
        ["modules.oos"] = ("Обработка рассинхрона", "Out-of-sync handling"),
        ["modules.oos.official"] = ("Официальная — остановить игру", "Official — stop the game"),
        ["modules.oos.continue"] = ("Продолжать игру · экспериментально", "Continue the game · experimental"),
        ["modules.oos.help"] = ("Официальный режим останавливает матч при рассинхроне. Экспериментальный EXE позволяет продолжить игру, но не устраняет возникшее различие состояния.", "Official handling stops the match on an out-of-sync event. The experimental EXE lets play continue but does not repair the divergent state."),
        ["modules.independent"] = ("Вражда независимых", "Independent faction hostility"),
        ["modules.independent.desc"] = ("Логова, лагеря и независимые города получают команды семейств", "Lairs, camps and independent towns receive family factions"),
        ["modules.independent.help"] = ("После генерации карты распределяет независимые объекты по командам семейств. Семейства враждуют между собой и с игроками; выбранные монстры также охотятся на животных. Одинаковая настройка обязательна у всех игроков.", "After map generation, assigns independent objects to family factions. Families fight each other and players; selected monsters also hunt wildlife. Every player must use the same setting."),
        ["modules.spawn"] = ("Частота блуждающих рот", "Roaming company frequency"),
        ["modules.spawn.standard"] = ("Стандартная", "Standard"),
        ["modules.spawn.x4"] = ("×4", "×4"),
        ["modules.spawn.help"] = ("Стандартный режим использует обычные интервалы и шансы. Режим ×4 вдвое сокращает время между проверками и удваивает шанс события — в среднем роты выходят примерно в четыре раза чаще. Настройка должна совпадать у всех игроков.", "Standard uses the normal intervals and chances. ×4 halves the interval and doubles the event chance, producing roaming companies about four times as often on average. Every player must use the same setting."),
        ["modules.roaming"] = ("Новые блуждающие роты", "Additional roaming companies"),
        ["modules.roaming.desc"] = ("Роты из лагерей поселений, фундаментов и выбранных логов", "Companies from settlement camps, foundation camps and selected lairs"),
        ["modules.roaming.help"] = ("Добавляет выход рот из лагерей бандитов, варваров, ракшасов и слаан на местах поселений и фундаментов, а также из логов пауков, скорпионов, Тёмного разлома и руин нежити. Настройка должна совпадать у всех игроков.", "Adds roaming companies from bandit, barbarian, Rhaksha and Slaan camps on settlement and foundation sites, plus spider and scorpion lairs, the Dark Rift and undead ruins. Every player must use the same setting."),
        ["modules.siege"] = ("Баланс осадных машин", "Siege engine balance"),
        ["modules.siege.desc"] = ("Особые осадные машины стоят 0,75 очка королевства за юнита", "Special siege engines cost 0.75 kingdom points per unit"),
        ["modules.siege.help"] = ("Меняет стоимость Багровой и Чумной катапульт, Баллисты Драконьего огня и Ворпальной машины на 0,75 очка королевства за юнита. Изменение в основном рассчитано на игры против ботов и должно совпадать у всех игроков.", "Sets the Crimson Catapult, Plague Catapult, Dragonfire Ballista and Vorpal Engine to 0.75 kingdom points per unit. This change is mainly balanced for matches against AI and must match for every player."),
        ["modules.multiplayer.note"] = ("Для сетевой игры игровые настройки и код конфигурации должны совпадать у всех участников.", "For multiplayer, gameplay settings and the configuration code must match for every participant."),
        ["configuration.title"] = ("Код конфигурации", "Configuration code"),
        ["configuration.desc"] = ("Отправьте этот код друзьям перед сетевой игрой", "Send this code to friends before a multiplayer match"),
        ["configuration.help"] = ("Короткая запись всех выбранных каналов и компонентов. Совпадающий код помогает убедиться, что у игроков одинаковые настройки, но не заменяет установку или обновление файлов.", "A compact record of every selected channel and component. A matching code helps confirm identical settings, but does not replace installing or updating files."),
        ["button.copyconfig"] = ("Скопировать код", "Copy code"),
        ["configuration.copied"] = ("Код конфигурации скопирован", "Configuration code copied"),
        ["diagnostics.title"] = ("Архив диагностики", "Diagnostic archive"),
        ["diagnostics.desc"] = ("Логи, синхлоги, дампы, версии модулей и хеши", "Logs, sync logs, dumps, module versions and hashes"),
        ["diagnostics.help"] = ("Собирает технический ZIP для разбора вылетов и рассинхронов. В него входят доступные логи, синхлоги, дампы, код конфигурации, список модулей и SHA-256. Дампы могут содержать фрагменты памяти — проверьте архив перед публичной отправкой.", "Builds a technical ZIP for investigating crashes and out-of-sync events. It includes available logs, sync logs, dumps, the configuration code, module list and SHA-256 values. Dumps may contain memory fragments, so review the archive before sharing it publicly."),
        ["button.diagnostics"] = ("Создать архив", "Create archive"),
        ["diagnostics.progress"] = ("Собираю архив диагностики…", "Creating diagnostic archive…"),
        ["diagnostics.ready"] = ("Архив диагностики создан: {0}", "Diagnostic archive created: {0}"),
        ["diagnostics.dialog"] = ("Сохранить архив диагностики", "Save diagnostic archive"),
        ["help.close"] = ("Понятно", "Got it"),
        ["news.title"] = ("Последние изменения", "Latest changes"),
        ["news.empty"] = ("После подключения сервера здесь появится история обновлений.", "Release notes will appear here after the update server is connected."),
        ["button.repair"] = ("Проверить файлы", "Verify files"),
        ["button.launch"] = ("Запустить игру", "Launch game"),
        ["button.browse"] = ("Выбрать", "Browse"),
        ["progress.checking"] = ("Проверяю обновления…", "Checking for updates…"),
        ["progress.downloading"] = ("Загрузка", "Downloading"),
        ["progress.installing"] = ("Установка и проверка файлов…", "Installing and verifying files…"),
        ["progress.beforelaunch"] = ("Применяю выбранные настройки перед запуском…", "Applying the selected settings before launch…"),
        ["error.title"] = ("Ошибка", "Error"),
        ["dialog.selectgame"] = ("Выберите папку Kohan II", "Select the Kohan II folder"),
    };
}
