<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PawsPatchLauncher</AssemblyName>
    <RootNamespace>PawsPatchLauncher</RootNamespace>
    <Version>0.7.7</Version>
    <AssemblyVersion>0.7.7.0</AssemblyVersion>
    <FileVersion>0.7.7.0</FileVersion>
    <ApplicationIcon>Assets\PawsPatch.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
    <Resource Include="Assets\PawsPatch.ico" />
    <Resource Include="Assets\ChatGlyphs\*.png" />
    <EmbeddedResource Include="launcher.config.json" />
    <EmbeddedResource Include="Assets\notification-soft-pluck.wav" />
    <EmbeddedResource Include="Assets\mod-guides.json" />
    <EmbeddedResource Include="Assets\Vanilla1372\autoexec.txt" />
    <EmbeddedResource Include="Assets\Vanilla1372\options_dialog.tgi" />
    <None Update="launcher.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
