"""Uniform city-list spacing. Native two-row bottom-panel layout is unchanged."""
import argparse,hashlib,json,struct,sys
from pathlib import Path
HOOK=0xE2618
ORIGINAL=bytes.fromhex('f30f108784000000')
def build(ks,image,cave):
    # Enter from the horizontal branch, after the original prologue and push esi.
    # EDI=this, [EBP-4]=child width, EBP-8/-C are native scratch locals.
    asm=f'''
        mov ecx,edi; call {image+0x2B6FC8}; fstp dword ptr [ebp-8];
        movss xmm0,[ebp-8]; movss xmm1,[edi+0x80]; addss xmm1,xmm1;
        subss xmm0,xmm1; subss xmm0,[ebp-4];
        mov eax,[edi+0x8c]; dec eax; cmp eax,1; jge divisor_ready; mov eax,1;
    divisor_ready:
        cvtsi2ss xmm1,eax; divss xmm0,xmm1;
        movss [ebp-0xc],xmm0;
        movss xmm0,[edi+0x80]; movss [ebp-8],xmm0;
        xor esi,esi;
    next_widget:
        cmp esi,[edi+0x8c]; jge done;
        push dword ptr [edi+0x84]; push dword ptr [ebp-8];
        mov eax,[edi+0x74]; mov ecx,[eax+esi*4]; call {image+0x2B701C};
        movss xmm0,[ebp-8]; addss xmm0,[ebp-0xc]; movss [ebp-8],xmm0;
        inc esi; jmp next_widget;
    done: jmp {image+0xE2844};
    '''
    return bytes(ks.asm(asm,cave)[0])
def main():
    p=argparse.ArgumentParser();p.add_argument('--legacy',type=Path,required=True);p.add_argument('--out',type=Path,required=True);a=p.parse_args()
    sys.path[:0]=[str(a.legacy/'lobby_colors_1372/deps_r15'),str(a.legacy/'pydeps_readable')]
    from keystone import Ks,KS_ARCH_X86,KS_MODE_32
    from capstone import Cs,CS_ARCH_X86,CS_MODE_32,CS_OP_IMM
    raw=(a.legacy/'k2_runtime_1372_20260904.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()=='b865d8206990c4f055c51de857f0b09b88ab5ee3b6ae74ee5232134001aa591c'
    assert raw[HOOK:HOOK+8]==ORIGINAL
    ks=Ks(KS_ARCH_X86,KS_MODE_32);code=build(ks,0x460000,0x10000000)
    md=Cs(CS_ARCH_X86,CS_MODE_32);md.detail=True;fixups=[]
    for ins in md.disasm(code,0x10000000):
        if ins.mnemonic in ('call','jmp') and ins.operands[0].type==CS_OP_IMM and 0x460000<=ins.operands[0].imm<0xAF0000:
            assert ins.imm_size==4;fixups.append(ins.address-0x10000000+ins.imm_offset)
    assert len(fixups)==3
    for ib,cb in [(0xe40000,0x21000000),(0x12000000,0x60000000)]:
        data=bytearray(code)
        for off in fixups:struct.pack_into('<I',data,off,(struct.unpack_from('<I',data,off)[0]+ib-0x460000+0x10000000-cb)&0xffffffff)
        assert data==build(ks,ib,cb)
    a.out.mkdir(parents=True,exist_ok=True);(a.out/'payload.bin').write_bytes(code)
    (a.out/'payload.json').write_text(json.dumps(dict(fixups=fixups),indent=2))
    src='// Generated by build_native.py\nusing System;\ninternal static class SettlementSlotsPayload {\ninternal static byte[] Build(uint image,uint cave) {\nbyte[] b=TerrainPatch.Hex("'+code.hex()+'");\n'
    for off in fixups:src+=f'Add(b,{off},unchecked(image-0x460000+0x10000000-cave));\n'
    src+='return b;}\nstatic void Add(byte[] b,int o,uint d){Buffer.BlockCopy(BitConverter.GetBytes(unchecked(BitConverter.ToUInt32(b,o)+d)),0,b,o,4);}\n}\n'
    (a.out/'SettlementSlotsPayload.cs').write_text(src)
    print('SETTLEMENT_SLOTS_BUILD_PASS',len(code),'bytes; 3 ASLR relocations')
if __name__=='__main__':main()
