"""Guarded Exhausted-only recovery when a terrain morale cap blocks native exit."""
import argparse, hashlib, json, struct, sys
from pathlib import Path
sys.dont_write_bytecode = True
HOOK = 0x274a1a
DECISION = 0x2147ec
ORIGINAL = bytes.fromhex('e8cdfdf9ff')
GUARD = bytes.fromhex('8b487ce8cdfdf9ff8b4e045e83f8020f84fe2e000083c1348b01ff6010')
DECISION_GUARD = bytes.fromhex('8bd18b42048b487085c9740c83792800753883792c0075320f57c00f2f42607329f30f104a5c0f2f8ab8000000771b0f2ec89ff6c4447b0f8b01ff505c33c984c00f94c18bc1c333c0c36a0258c3')

def build(ks, image, cave):
    return bytes(ks.asm(f'''
        push ecx
        call {image+DECISION}
        pushfd
        pushad
        mov esi,[esp+36]
        sub esp,528
        lea eax,[esp+15]
        and eax,0xfffffff0
        fxsave [eax]
        push eax
        inc dword ptr [{cave+0x1000}]
        cmp dword ptr [esp+560],1
        ja done
        mov eax,[esi+0x60]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        mov eax,[esi+0x5c]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        mov eax,[esi+0xb8]
        and eax,0x7fffffff
        cmp eax,0x7f800000
        jae done
        xorps xmm0,xmm0
        movss xmm1,[esi+0x60]
        ucomiss xmm1,xmm0
        jbe done
        ucomiss xmm1,[esi+0xb8]
        ja done
        movss xmm0,[esi+0x5c]
        ucomiss xmm0,xmm1
        jb done
        mov dword ptr [esp+560],2
        inc dword ptr [{cave+0x1004}]
    done:
        pop eax
        fxrstor [eax]
        add esp,528
        popad
        popfd
        lea esp,[esp+4]
        ret
    ''', cave)[0])

def main():
    p=argparse.ArgumentParser();p.add_argument('--legacy',type=Path,required=True);p.add_argument('--out',type=Path,required=True);a=p.parse_args()
    sys.path[:0]=[str(a.legacy/'lobby_colors_1372/deps_r15'),str(a.legacy/'pydeps_readable')]
    from keystone import Ks,KS_ARCH_X86,KS_MODE_32
    from capstone import Cs,CS_ARCH_X86,CS_MODE_32,CS_OP_MEM,CS_OP_IMM
    raw=(a.legacy/'k2_runtime_1372_20260904.bin').read_bytes()
    assert hashlib.sha256(raw).hexdigest()=='b865d8206990c4f055c51de857f0b09b88ab5ee3b6ae74ee5232134001aa591c'
    assert raw[HOOK:HOOK+5]==ORIGINAL
    assert raw[HOOK-3:HOOK-3+len(GUARD)]==GUARD
    assert raw[DECISION:DECISION+len(DECISION_GUARD)]==DECISION_GUARD
    ks=Ks(KS_ARCH_X86,KS_MODE_32);md=Cs(CS_ARCH_X86,CS_MODE_32);md.detail=True
    image,cave=0x460000,0x10000000;code=build(ks,image,cave);fixups=[]
    for ins in md.disasm(code,cave):
        for op in ins.operands:
            if op.type==CS_OP_MEM and not op.mem.base and not op.mem.index and cave<=op.mem.disp<cave+8192:
                fixups.append((ins.address-cave+ins.disp_offset,0,1))
            elif op.type==CS_OP_IMM and image<=op.imm<image+0x690000:
                fixups.append((ins.address-cave+ins.imm_offset,1,-1 if ins.mnemonic in ('call','jmp') else 0))
    for ib,cb in [(0xE40000,0x21000000),(0x12000000,0x60000000),(0x740000,0x31000000)]:
        relocated=bytearray(code)
        for off,im,cv in fixups:
            struct.pack_into('<I',relocated,off,(struct.unpack_from('<I',relocated,off)[0]+im*(ib-image)+cv*(cb-cave))&0xffffffff)
        assert bytes(relocated)==build(ks,ib,cb)
    assert len(code)<0xfc0
    a.out.mkdir(parents=True,exist_ok=True)
    (a.out/'exhaustion.bin').write_bytes(code)
    (a.out/'exhaustion.json').write_text(json.dumps(dict(image=image,cave=cave,hook=HOOK,guard=GUARD.hex(),fixups=fixups),indent=2))
    src='// Generated by build_native.py.\nusing System;\ninternal static class ExhaustionRecoveryPayload {\n internal static byte[] Build(uint image,uint cave) {\n byte[] b=TerrainPatch.Hex("'+code.hex()+'");\n'
    for off,im,cv in fixups:
        expr=[]
        if im:expr.append('(image-0x460000)')
        if cv==1:expr.append('(cave-0x10000000)')
        elif cv==-1:expr.append('(0x10000000-cave)')
        src+=f' Add(b,{off},unchecked({"+".join(expr)}));\n'
    src+=' return b;\n }\n static void Add(byte[] b,int o,uint d){Buffer.BlockCopy(BitConverter.GetBytes(unchecked(BitConverter.ToUInt32(b,o)+d)),0,b,o,4);}\n}\n'
    (a.out/'ExhaustionRecoveryPayload.cs').write_text(src)
    print(f'EXHAUSTION_BUILD_PASS: {len(code)} bytes, {len(fixups)} relocations; Exhausted call site only')

if __name__=='__main__':main()
