internal static partial class PawAssistantRuntime
{
    private static readonly string[,] cityAdvice = {
        {
            "Priority: final city center upgrade, resource targets, gold income, then random development. If gold is insufficient, the assistant saves for the selected priority. During the resource stage, a market wins only if its gold gain after shortage costs exceeds that of the resource building. Markets use only their best gold-increasing branch; without one, they are not upgraded. All queued work and the gold reserve are respected. Settings are saved per match; new matches use defaults.",
            "Приоритет: последнее улучшение центра, цели по ресурсам, доход золота, затем случайное развитие. Если золота не хватает, автоулучшение копит на выбранную приоритетную постройку. На этапе ресурсов рынок выбирается, только если его прирост золота после расходов на дефицит выше, чем у ресурсной постройки. Рынки улучшаются только по лучшей золотой ветке; без прироста золота не улучшаются. Учитываются вся очередь и запас золота. Настройки сохраняются для партии; новая партия начинается со стандартных.",
            "Priorität: letzte Aufwertung des Stadtzentrums, Ressourcenziele, Goldertrag, dann zufälliger Ausbau. Reicht das Gold nicht aus, wird für die gewählte vorrangige Maßnahme gespart. In der Ressourcenphase wird ein Markt nur bevorzugt, wenn sein Goldzuwachs nach Abzug der Defizitkosten höher ist als der des Ressourcengebäudes. Märkte nutzen nur den Ausbauzweig mit dem höchsten Goldzuwachs; ohne einen solchen werden sie nicht aufgewertet. Bauwarteschlange und Goldreserve werden berücksichtigt. Einstellungen gelten pro Partie; neue Partien starten mit Standardwerten.",
            "Priorité : dernière amélioration du centre-ville, objectifs de ressources, revenu en or, puis développement aléatoire. Si l’or manque, l’assistant économise pour l’action prioritaire choisie. À l’étape des ressources, un marché ne passe en premier que si son gain d’or après le coût des pénuries dépasse celui du bâtiment de ressources. Les marchés suivent uniquement la branche offrant le plus d’or supplémentaire ; sans elle, ils ne sont pas améliorés. Toute la file et la réserve d’or sont prises en compte. Réglages par partie ; valeurs par défaut pour une nouvelle partie.",
            "Priorita: poslední vylepšení centra města, cíle surovin, příjem zlata, poté náhodný rozvoj. Pokud zlato nestačí, automatika šetří na vybranou prioritní stavbu. Při plnění cílů surovin dostane tržiště přednost pouze tehdy, když jeho přírůstek zlata po nákladech na nedostatek překoná surovinovou budovu. Tržiště využívají jen větev s nejvyšším přírůstkem zlata; bez takové větve se nevylepšují. Zohledňuje se celá fronta i zlatá rezerva. Nastavení se ukládá pro každou partii; nová partie začíná s výchozími hodnotami.",
            "Пріоритет: останнє поліпшення центру, цілі щодо ресурсів, дохід золота, потім випадковий розвиток. Якщо золота бракує, автополіпшення накопичує його на обрану пріоритетну будівлю. На етапі ресурсів ринок обирається, лише якщо його приріст золота після витрат на дефіцит вищий, ніж у ресурсної будівлі. Ринки поліпшуються лише за найкращою золотою гілкою; без приросту золота не поліпшуються. Враховуються вся черга і золотий резерв. Налаштування зберігаються для партії; нова партія починається зі стандартних."
        },
        {
            "No available order currently meets the resource protection and queue constraints.",
            "Сейчас нет доступного приказа, допустимого с учётом защиты ресурсов и очереди строительства.",
            "Derzeit erfüllt kein verfügbarer Auftrag die Anforderungen des Ressourcenschutzes und der Bauwarteschlange.",
            "Aucun ordre disponible ne respecte actuellement la protection des ressources et la file de construction.",
            "Žádný dostupný příkaz nyní nesplňuje podmínky ochrany surovin a fronty staveb.",
            "Зараз немає доступного наказу, допустимого з урахуванням захисту ресурсів і черги будівництва."
        },
        {"Could not read match settings", "Не удалось прочитать настройки партии", "Partieeinstellungen konnten nicht gelesen werden", "Impossible de lire les réglages de la partie", "Nastavení partie se nepodařilo načíst", "Не вдалося прочитати налаштування партії"},
        {"Auto-upgrade is paused. See the Paw’s Patch log for details.", "Автоулучшение приостановлено. Подробности в журнале Paw’s Patch.", "Der automatische Ausbau ist pausiert. Einzelheiten stehen im Protokoll von Paw’s Patch.", "L’amélioration automatique est suspendue. Consultez le journal de Paw’s Patch.", "Automatická vylepšení jsou pozastavena. Podrobnosti jsou v protokolu Paw’s Patch.", "Автополіпшення призупинено. Подробиці в журналі Paw’s Patch."}
    };
    private static string CityAdvice(int index) {return cityAdvice[index,(int)PawGameText.LanguageId];}
}
